version: '3'
services:
  website:
    image: ${CONTAINER_REGISTRY}perfectengineering/asowunmi-website:${WEBSITE_VERSION}
    env_file: .env
    volumes:
      - ${MEDIA_UPLOAD_PATH}:/var/www/html/wp-content/uploads
    ports:
      - "9000:80"
    restart: always
