version: '3'
services:
  website:
    environment:
      WORDPRESS_DB_HOST: db:3306
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: mysql:5.7.21
    volumes:
      - ${DATABASE_VOLUME_PATH}:/var/lib/mysql
    restart: always
    env_file:
      - .env
