version: '3'
services:
  website:
    image: ${CONTAINER_REGISTRY}perfectengineering/asowunmi-website:${WEBSITE_VERSION}
    volumes:
      - ${MEDIA_UPLOAD_PATH}:/var/www/html/wp-content/uploads
    ports:
      - "80:80"
    restart: always