<?php
class Umbala_Default_Options {

    function __construct() {

        if (!class_exists('ReduxFramework')) {
            $this->_load_default_options();
        }
    }

    /** Load default options if redux is not installed * */
    function _load_default_options() {
        global $umbala_opt;
        $umbala_opt = array(
            'alus_layout' => 'full-width',
            'alus_gmap_api_key' => '',
            'alus_back_to_top_button' => false,
            'alus_back_to_top_button_on_mobile' => false,
            'alus_logo' => array(
                'url' => get_template_directory_uri() . '/assets/images/logo.png',
            ),
            'alus_logo_sticky' => array(
                'url' => get_template_directory_uri() . '/assets/images/logo.png',
            ),
            'alus_favicon' => array(
                'url' => get_template_directory_uri() . '/assets/images/icon.png',
            ),
            'alus_favicon_retina' => array(
                'url' => get_template_directory_uri() . '/assets/images/icon.png',
            ),
            'alus_page_title' => 1,
            'alus_breadcrumbs' => 1,
            'alus_breadcrumb_layout' => 'layout1',
            'alus_bg_breadcrumbs' => array(
                'background-image' => '',
            ),
            'alus_enable_popup' => 0,
            'alus_header_layout' => 'layout1',
            'alus_header_mobile_layout' => 'center',
            'alus_enable_sticky_header' => 1,
            'alus_header_top_bar' => 1,
            'alus-top-bar-color' => '#999',
            'alus-top-bar-bg' => '#fff',
            'alus_header_contact_information' => '',
            'alus_middle_header_content' => '',
            'alus_header_currency' => 0,
            'alus_header_language' => 0,
            'alus_enable_tiny_shopping_cart' => 1,
            'alus_tiny_cart_style' => 'dropdown',
            'alus_enable_search' => 1,
            'alus_ajax_search' => 0,
            'alus_ajax_search_number_result' => 3,
            'alus_enable_tiny_account' => 0,
            'alus_login_style' => 'dropdown',
            'alus_enable_tiny_wishlist' => 1,
            'alus_primary_color' => '#d85c5c',
            'alus_secondary_color' => '#444',
            'alus_body_background_color' => '#ffffff',
            'alus_title_font' => 1,
            'alus_title_font_family' => 'Arial',
            'alus_title_font_google' => array(
                'color' => "#000000",
                'google' => true,
                'font-family' => 'Lato',

            ),
            'alus_body_font' => array(
                'color' => "#000000",
                'google' => true,
                'font-family' => 'Lato',
            ),
            'alus_font_size_body' => '14',
            'alus_line_height_body' => '24',
            'alus_effect_hover_product_style' => 'style-1',
            'alus_effect_product' => '1',
            'alus_effect_hover_product_img' => 'zoom-long',
            'alus_product_gallery_number' => 3,
            'alus_enable_quickshop' => '1',
            'alus_enable_lazyload_product' => 0,
            'alus_enable_catalog_mode' => '0',
            'alus_product_sale_percentage' => 0,
            'alus_product_feature_label' => 1,
            'alus_product_out_of_stock_label' => 1,
            'alus_prod_cat_layout' => 'full-width',
            'alus_prod_cat_left_sidebar' => 'product-category-sidebar',
            'alus_prod_cat_right_sidebar' => 'product-category-sidebar',
            'alus_show_sidebar_button' => 1,
            'alus_show_filters_area' => 0,
            'alus_prod_cat_columns' => '3',
            'alus_prod_per_page' => 9,
            'alus_enable_color_swatches' => 0,
            'alus_enable_grid_list' => 1,
            'alus_grid_list_default' => 'grid',
            'alus_prod_cat_thumbnail' => 1,
            'alus_prod_cat_label' => 1,
            'alus_prod_cat_cat' => 0,
            'alus_prod_cat_title' => 1,
            'alus_prod_cat_sku' => 0,
            'alus_prod_cat_rating' => 1,
            'alus_prod_cat_price' => 1,
            'alus_prod_cat_add_to_cart' => 1,
            'alus_prod_cat_grid_desc' => 0,
            'alus_prod_cat_grid_desc_words' => 8,
            'alus_prod_cat_list_desc' => 1,
            'alus_prod_cat_list_desc_words' => 50,
            'alus_prod_layout' => 'full-width',
            'alus_prod_left_sidebar' => 'product-detail-sidebar',
            'alus_prod_right_sidebar' => 'product-detail-sidebar',
            'alus_product_zoom' => 1,
            'alus_product_lightbox' => 0,
            'alus_product_zoom_button' => 0,
            'alus_prod_variation_swatches' => 1,
            'alus_prod_thumbnail' => 1,
            'alus_prod_label' => 0,
            'alus_show_prod_navigation' => 0,
            'alus_prod_title' => 1,
            'alus_prod_title_in_content' => 0,
            'alus_prod_rating' => 1,
            'alus_prod_sku' => 0,
            'alus_prod_availability' => 1,
            'alus_prod_excerpt' => 1,
            'alus_prod_count_down' => 1,
            'alus_prod_price' => 1,
            'alus_prod_add_to_cart' => 1,
            'alus_prod_cat' => 1,
            'alus_prod_tag' => 1,
            'alus_prod_sharing' => 0,
            'alus_show_prod_size_chart' => 0,
            'alus_prod_size_chart' => array('url' => get_template_directory_uri() . '/assets/images/size-chart.jpg'),
            'alus_prod_thumbnails_style' => 'horizontal',
            'alus_product_sticky_bar' => 0,
            'alus_prod_tabs' => 1,
            'alus_prod_style_tabs' => 'default',
            'alus_prod_tabs_position' => 'after_summary',
            'alus_prod_custom_tab' => 0,
            'alus_prod_custom_tab_title' => 'Custom Tab',
            'alus_prod_custom_tab_content' => '',
            'alus_prod_ads_banner' => 0,
            'alus_prod_ads_banner_content' => '',
            'alus_prod_upsells' => 0,
            'alus_prod_related' => 1,
            'alus_blog_layout' => 'right-sidebar',
            'alus_blog_left_sidebar' => 'blog-sidebar',
            'alus_blog_right_sidebar' => 'blog-sidebar',
            'alus_blog_thumbnail' => 1,
            'alus_blog_lazyload' => 0,
            'alus_blog_date' => 1,
            'alus_blog_title' => 1,
            'alus_blog_author' => 1,
            'alus_blog_comment' => 0,
            'alus_blog_count_view' => 0,
            'alus_blog_read_more' => 1,
            'alus_blog_categories' => 1,
            'alus_blog_tags' => 1,
            'alus_blog_excerpt' => 1,
            'alus_blog_excerpt_strip_tags' => 0,
            'alus_blog_excerpt_max_words' => -1,
            'alus_blog_details_layout' => 'right-sidebar',
            'alus_blog_details_left_sidebar' => 'blog-detail-sidebar',
            'alus_blog_details_right_sidebar' => 'blog-detail-sidebar',
            'alus_blog_details_thumbnail' => 1,
            'alus_blog_details_date' => 1,
            'alus_blog_details_title' => 1,
            'alus_blog_details_title' => 1,
            'alus_blog_details_content' => 1,
            'alus_blog_details_tags' => 1,
            'alus_blog_details_sharing' => 0,
            'alus_blog_details_navigation' => 0,
            'alus_blog_details_count_view' => 0,
            'alus_blog_details_categories' => 1,
            'alus_blog_details_author_box' => 0,
            'alus_blog_details_related_posts' => 0,
            'alus_blog_details_comment_form' => 1,
        );
    }
}
new Umbala_Default_Options();

/* Function to get option from Redux Framework */
function umbala_get_opt($slug = '') {
    global $umbala_opt;

    return isset($umbala_opt[$slug]) ? $umbala_opt[$slug] : '';
}

?>